In [2]:
# https://learnopencv.com/fine-tuning-bert/

In [3]:
from pathlib import Path
from typing import Literal

import torch

from collections.abc import Callable

from datasets import Dataset, load_dataset, load_from_disk
from transformers import (
    AutoTokenizer,
    DataCollatorWithPadding,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    pipeline,
)

import evaluate
import glob
import json
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

from pathlib import Path
from datetime import datetime

import sys

sys.path.insert(0, str(Path.cwd().parent))


from finetuning.commons import PipelineData, prepare_data, parse_pubtator, build_training_samples, samples_to_rels_like_df
from dataset_preparation.perturbations import BIORED_RELATION_TYPES, NO_RELATION_LABEL
from dataset_preparation.prepare_pure_biored import build_pure_biored_samples, compute_relation_distance_stats

In [ ]:

USE_CACHE = True

# MODEL = 'NeuML/pubmedbert-base-embeddings'
MODEL = 'bioformers/bioformer-8L'

DATASET_NAME: Literal["BioRed", "BioRedPerturbated"] = "BioRed"

F1_AVERAGE: Literal["micro", "macro", "weighted"] = "micro"

OUT_DIR = f"relations-bert_{MODEL.replace("/", "-")}_{datetime.now():%Y-%m-%d_%H-%M-%S}_{DATASET_NAME}_{F1_AVERAGE}"
# OUT_DIR = "relations-bert-BioFormer8L-2026-07-01_22-24-16_BioRedPerturbated_micro"

In [5]:



# NOTE: these are the defaults might change according to avaibale VRAM
# -> BATCH SIZE and LR are halved if less than 8GB of VRAM is detected
BATCH_SIZE = 32
NUM_PROCS = 32
LR = 0.00005
EPOCHS = 10
CACHE_DIR = Path("cache")

PUBTATOR_FILE_TRAIN = Path.home() / "git/LLMs_for_NEL/Data/BioRED/Train.PubTator"
PUBTATOR_FILE_DEV = Path.home() / "git/LLMs_for_NEL/Data/BioRED/Dev.PubTator"
PUBTATOR_FILE_TEST = Path.home() / "git/LLMs_for_NEL/Data/BioRED/Test.PubTator"



def load_or_cache(split: str, prefix: str, build: Callable[[], Dataset], use_cache: bool = True) -> Dataset:
    """Load a Hugging Face ``Dataset`` from disk cache or build and persist it.

    Cached data is stored under ``CACHE_DIR / f"{prefix}_{split}"`` (default: ``cache/``).
    On a cache hit, ``load_from_disk`` is used and ``build`` is not called.
    On a miss, ``build()`` runs once, the result is saved with ``save_to_disk``, then returned.

    Args:
        split: Split identifier used in the cache directory name (e.g. ``"train"``, ``"validation"``).
        prefix: Stage prefix distinguishing pipeline steps (e.g. ``"raw"``, ``"tokenized"``).
        build: Zero-argument callable that produces the dataset when the cache is missing.

    Returns:
        The dataset for the given split, either loaded from cache or freshly built.

    Examples:
        Download a Hub split and cache it as ``cache/raw_train/``::

            train = load_or_cache(
                "train",
                "raw",
                lambda: load_dataset("ccdv/arxiv-classification", split="train"),
            )

        Tokenize an in-memory split and cache as ``cache/tokenized_train/``::

            tokenized_train = load_or_cache(
                "train",
                "tokenized",
                lambda: train.map(preprocess_function, batched=True, batch_size=32),
            )

    Note:
        Delete the matching folder under ``cache/`` to force a rebuild after changing
        ``build``, the source data, or preprocessing.
    """
    cache_path = CACHE_DIR / f"{prefix}_{split}"
    if cache_path.exists() and use_cache:
        print(f"Loading {prefix} {split} from cache/")
        return load_from_disk(cache_path)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    dataset = build()
    dataset.save_to_disk(cache_path)
    return dataset

In [6]:
MODE: str = "cpu"
if torch.backends.mps.is_available():
    MODE = "mps"
elif torch.cuda.is_available():
    MODE = "cuda"
else:
    print("No GPU or MPS available - uising CPU")

print(f"Using {MODE} for training")


hardware_specific_args = {}

if MODE == "mps":
    hardware_specific_args["fp16"] = False
    hardware_specific_args["dataloader_num_workers"] = 0
    hardware_specific_args["per_device_train_batch_size"] = BATCH_SIZE
    hardware_specific_args["per_device_eval_batch_size"] = BATCH_SIZE
    hardware_specific_args["learning_rate"] = LR
    

elif MODE == "cuda":
    # Check total GPU VRAM 
    total_vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024 ** 3)
    print(f"CUDA device VRAM: {total_vram_gb:.2f} GB")

    # Default: assume >8GB VRAM
    batch_div = 1
    lr_div = 1

    # 2070super only has 8gigs of VRAM :')
    if total_vram_gb <= 8.5:
        print("Detected ~8GB of VRAM or less, reducing batch size and learning rate.")
        batch_div = 2
        lr_div = 2

    hardware_specific_args["fp16"] = True
    hardware_specific_args["per_device_train_batch_size"] = BATCH_SIZE // batch_div
    hardware_specific_args["per_device_eval_batch_size"] = BATCH_SIZE // batch_div
    hardware_specific_args["learning_rate"] = LR / lr_div

    print(f"Using {hardware_specific_args['per_device_train_batch_size']} for training")
    print(f"Using {hardware_specific_args['per_device_eval_batch_size']} for evaluation")
    print(f"Using {hardware_specific_args['learning_rate']} for learning rate")

Using cuda for training
CUDA device VRAM: 7.57 GB
Detected ~8GB of VRAM or less, reducing batch size and learning rate.
Using 16 for training
Using 16 for evaluation
Using 2.5e-05 for learning rate

In [7]:
training_args = TrainingArguments(
    output_dir=OUT_DIR,
    num_train_epochs=EPOCHS,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_f1_micro",
    greater_is_better=True,
    save_total_limit=EPOCHS,
    report_to="tensorboard",
    **hardware_specific_args,
)

In [8]:
RELATION_LABELS: list[str] = BIORED_RELATION_TYPES + [NO_RELATION_LABEL]
label2id: dict[str, int] = {name: idx for idx, name in enumerate(RELATION_LABELS)}
id2label: dict[int, str] = {idx: name for name, idx in label2id.items()}
MASK_TOKEN = "[MASK]"

def build_samples(
    pubtator_file: Path,
    dataset_name: Literal["BioRed", "BioRedPerturbated"] = DATASET_NAME,
    label_map: dict[str, int] = label2id,
    mask_token: str = MASK_TOKEN,
    no_relation_label: str = NO_RELATION_LABEL,
    parsed: tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame] | None = None,
    distance_stats: dict[str, float] | None = None,
    verbose: bool = True,
) -> pd.DataFrame:
    """Parse a PubTator file and build the relation-classification samples DataFrame.

    Args:
        pubtator_file: Path to the PubTator file to parse.
        dataset_name: Which sample-building strategy to use. ``"BioRed"`` uses gold
            relations plus distance-matched NoRelation examples, ``"BioRedPerturbated"``
            uses the perturbated training samples.
        label_map: Mapping from relation label name to integer class id.
        mask_token: Token used as the relation placeholder in the prompt.
        no_relation_label: Label assigned to ``false_positive`` (unrelated) pairs.
        parsed: Optional pre-parsed ``(meta, anns, rels)`` tuple to avoid re-reading the file.
        distance_stats: Train-fit distance thresholds for NoRelation sampling on dev/test.
        verbose: Whether to print NoRelation sampling diagnostics.

    Returns:
        A DataFrame with ``prompt``, ``target_relation`` and ``label`` columns,
        restricted to ``gold`` and ``false_positive`` perturbations.
    """
    if parsed is not None:
        meta_df, anns_df, rels_df = parsed
    else:
        meta_df, anns_df, rels_df = parse_pubtator(pubtator_file)

    if dataset_name == "BioRedPerturbated":
        samples = build_training_samples(meta_df, anns_df, rels_df)

    elif dataset_name == "BioRed":
        # Original BioRED: gold relations + distance-matched NoRelation examples.
        samples = build_pure_biored_samples(
            meta_df,
            anns_df,
            rels_df,
            distance_stats=distance_stats,
            verbose=verbose,
        )

    else:
        raise ValueError(f"Unknown dataset_name: {dataset_name!r}")

    samples = samples_to_rels_like_df(samples)

    # Gold relations (8 types) + unrelated entity pairs (NoRelation).
    samples = samples[samples["perturbation"].isin(["gold", "false_positive"])].copy()

    samples["prompt"] = samples.apply(
        lambda row: (
            f"Relation: {row['entity_a_text']} -> {mask_token} -> {row['entity_b_text']}\n"
            f"Context: {row['abstract']}"
        ),
        axis=1,
    )
    samples["target_relation"] = np.where(
        samples["perturbation"] == "false_positive",
        no_relation_label,
        samples["relation_type"],
    )
    samples["label"] = samples["target_relation"].map(label_map)
    return samples


# Official BioRED splits: Train for fitting, Dev for validation/checkpoint selection, Test held out.
train_parsed = parse_pubtator(PUBTATOR_FILE_TRAIN)
train_distance_stats = compute_relation_distance_stats(*train_parsed)

train_df = build_samples(
    PUBTATOR_FILE_TRAIN,
    parsed=train_parsed,
    distance_stats=train_distance_stats,
)
val_df = build_samples(
    PUBTATOR_FILE_DEV,
    distance_stats=train_distance_stats,
    verbose=False,
)
test_df = build_samples(
    PUBTATOR_FILE_TEST,
    distance_stats=train_distance_stats,
    verbose=False,
)

train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
valid_dataset = Dataset.from_pandas(val_df.reset_index(drop=True))
test_dataset = Dataset.from_pandas(test_df.reset_index(drop=True))
print(f"Classes: {len(RELATION_LABELS)}")
print(f"Train: {len(train_df)}, Dev: {len(val_df)}, Test: {len(test_df)}")
print(train_df["target_relation"].value_counts())

Related-entity distance statistics (characters):
  pairs  : 4178
  mean   : 73.8
  median : 37.0
  std    : 121.7
  min    : 0.0
  max    : 1599.0
Built 4178 gold relations and 4162 NoRelation examples.
{'pmid': '10491763', 'relation_type': 'Association', 'id_1': '3175', 'id_2': 'D003924', 'entity_a_text': 'hepatocyte nuclear factor (HNF)-6', 'entity_b_text': 'Type II (non-insulin-dependent) diabetes mellitus', 'perturbation': 'gold', 'label': 1, 'abstract': 'The transcription factor hepatocyte nuclear factor (HNF)-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in the HNF-6 gene is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of the HNF-6 gene. We then examined them on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of the Pro75Ala polymorphism was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of the polymorphism did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of the HNF-6 gene are not associated with Type II diabetes or with changes in insulin responses to glucose among the Caucasians examined.'}
{'pmid': '14510914', 'relation_type': 'Positive_Correlation', 'id_1': 'c|DEL|1314_1328|', 'id_2': 'D003409', 'entity_a_text': 'deletion of the coding sequence (nt 1314 through nt 1328)', 'entity_b_text': 'Congenital hypothyroidism', 'perturbation': 'gold', 'label': 1, 'abstract': "OBJECTIVE: Iodide transport defect (ITD) is a rare disorder characterised by an inability of the thyroid to maintain an iodide gradient across the basolateral membrane of thyroid follicular cells, that often results in congenital hypothyroidism. When present the defect is also found in the salivary glands and gastric mucosa and it has been shown to arise from abnormalities of the sodium/iodide symporter (NIS). PATIENT: We describe a woman with hypothyroidism identified at the 3rd month of life. The diagnosis of ITD was suspected because of nodular goitre, and little if any iodide uptake by the thyroid and salivary glands. Treatment with iodide partially corrected the hypothyroidism; however, long-term substitution therapy with L-thyroxine was started. MEASUREMENTS: Thyroid radioiodide uptake was only 1.4% and 0.3% at 1 and 24 h after the administration of recombinant human TSH. The saliva to plasma I- ratio was 1.1 indicating that the inability of the thyroid gland to concentrate I- was also present in the salivary glands. RESULTS: Analysis of the patient's NIS gene revealed a 15 nucleotide (nt) deletion of the coding sequence (nt 1314 through nt 1328) and the insertion of 15 nt duplicating the first 15 nt of the adjacent intron. The patient was homozygous for this insertion/deletion, while both consanguineous parents were heterozygous. This deletion predicts the production of a protein lacking the five terminal amino acids of exon XI (439-443) which are located in the 6th intracellular loop. COS-7 cells transfected with a vector expressing the mutant del-(439-443) NIS failed to concentrate iodide, suggesting that the mutation was the direct cause of the ITD in this patient. CONCLUSION: In conclusion we describe the first Italian case of congenital hypothyroidism due to a new deletion in the NIS gene."}
{'pmid': '15485686', 'relation_type': 'Association', 'id_1': 'D001919', 'id_2': '6331', 'entity_a_text': 'bradycardia', 'entity_b_text': 'Na(v)1.5', 'perturbation': 'gold', 'label': 1, 'abstract': 'OBJECTIVE: Congenital long QT syndrome (LQTS) with in utero onset of the rhythm disturbances is associated with a poor prognosis. In this study we investigated a newborn patient with fetal bradycardia, 2:1 atrioventricular block and ventricular tachycardia soon after birth. METHODS: Mutational analysis and DNA sequencing were conducted in a newborn. The 2:1 atrioventricular block improved to 1:1 conduction only after intravenous lidocaine infusion or a high dose of mexiletine, which also controlled the ventricular tachycardia. RESULTS: A novel, spontaneous LQTS-3 mutation was identified in the transmembrane segment 6 of domain IV of the Na(v)1.5 cardiac sodium channel, with a G-->A substitution at codon 1763, which changed a valine (GTG) to a methionine (ATG). The proband was heterozygous but the mutation was absent in the parents and the sister. Expression of this mutant channel in tsA201 mammalian cells by site-directed mutagenesis revealed a persistent tetrodotoxin-sensitive but lidocaine-resistant current that was associated with a positive shift of the steady-state inactivation curve, steeper activation curve and faster recovery from inactivation. We also found a similar electrophysiological profile for the neighboring V1764M mutant. But, the other neighboring I1762A mutant had no persistent current and was still associated with a positive shift of inactivation. CONCLUSIONS: These findings suggest that the Na(v)1.5/V1763M channel dysfunction and possible neighboring mutants contribute to a persistent inward current due to altered inactivation kinetics and clinically congenital LQTS with perinatal onset of arrhythmias that responded to lidocaine and mexiletine.'}
Classes: 9
Train: 8340, Dev: 2323, Test: 2326
target_relation
NoRelation              4162
Association             2192
Positive_Correlation    1089
Negative_Correlation     763
Bind                      61
Cotreatment               31
Comparison                28
Drug_Interaction          11
Conversion                 3
Name: count, dtype: int64

In [9]:
train_dataset[0]

{'pmid': '10491763',
 'relation_type': 'Association',
 'id_1': '3175',
 'id_2': 'D003924',
 'entity_a_text': 'hepatocyte nuclear factor (HNF)-6',
 'entity_b_text': 'Type II (non-insulin-dependent) diabetes mellitus',
 'perturbation': 'gold',
 'label': 2,
 'abstract': 'The transcription factor hepatocyte nuclear factor (HNF)-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in the HNF-6 gene is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of the HNF-6 gene. We then examined them on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of the Pro75Ala polymorphism was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of the polymorphism did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of the HNF-6 gene are not associated with Type II diabetes or with changes in insulin responses to glucose among the Caucasians examined.',
 'prompt': 'Relation: hepatocyte nuclear factor (HNF)-6 -> [MASK] -> Type II (non-insulin-dependent) diabetes mellitus\nContext: The transcription factor hepatocyte nuclear factor (HNF)-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in the HNF-6 gene is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of the HNF-6 gene. We then examined them on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of the Pro75Ala polymorphism was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of the polymorphism did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of the HNF-6 gene are not associated with Type II diabetes or with changes in insulin responses to glucose among the Caucasians examined.',
 'target_relation': 'Association'}

In [10]:
# display how many no relation there are
print(train_df["target_relation"].value_counts())

print()

# number of entries that are not no relation
print(train_df[train_df["target_relation"] != NO_RELATION_LABEL].shape[0])

target_relation
NoRelation              4162
Association             2192
Positive_Correlation    1089
Negative_Correlation     763
Bind                      61
Cotreatment               31
Comparison                28
Drug_Interaction          11
Conversion                 3
Name: count, dtype: int64

4178

In [11]:
print(f"Relation classification: {len(RELATION_LABELS)} classes")
print("label2id:", label2id)

Relation classification: 9 classes
label2id: {'Positive_Correlation': 0, 'Negative_Correlation': 1, 'Association': 2, 'Comparison': 3, 'Cotreatment': 4, 'Drug_Interaction': 5, 'Bind': 6, 'Conversion': 7, 'NoRelation': 8}

In [12]:
tokenizer = AutoTokenizer.from_pretrained(MODEL)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [13]:
def preprocess_function(examples, key: str = "prompt"):
    return tokenizer(
        examples[key],
        truncation=True,
        padding=True,
        max_length=512,
    )

In [14]:
def _tokenize(dataset: Dataset) -> Dataset:
    return dataset.map(
        preprocess_function,
        batched=True,
        batch_size=BATCH_SIZE,
        num_proc=NUM_PROCS,
    )

# used for training
tokenized_train = load_or_cache(
    "train", f"{DATASET_NAME}_relation_type_tokenized_{hash(str(train_dataset))}", lambda: _tokenize(train_dataset), use_cache=USE_CACHE
)

# used for validation
tokenized_valid = load_or_cache(
    "valid", f"{DATASET_NAME}_relation_type_tokenized_{hash(str(valid_dataset))}", lambda: _tokenize(valid_dataset), use_cache=USE_CACHE
)

# used for final testing
tokenized_test = load_or_cache(
    "test", f"{DATASET_NAME}_relation_type_tokenized_{hash(str(test_dataset))}", lambda: _tokenize(test_dataset), use_cache=USE_CACHE
)

Parameter 'function'=<function preprocess_function at 0x7176fc517920> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only shown once. Subsequent hashing failures won't be shown.
Map (num_proc=32): 100%|██████████| 8340/8340 [00:06<00:00, 1263.79 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 8340/8340 [00:00<00:00, 212358.22 examples/s]
Map (num_proc=32): 100%|██████████| 2323/2323 [00:03<00:00, 706.35 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 2323/2323 [00:00<00:00, 133300.98 examples/s]
Map (num_proc=32): 100%|██████████| 2326/2326 [00:03<00:00, 771.45 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 2326/2326 [00:00<00:00, 124724.51 examples/s]

In [15]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [ ]:
# Sanity check: no sample (identified by pmid + id_1 + id_2) appears in more than one split.
# def _key_set(dataset: Dataset) -> set[tuple[str, str, str]]:
#     """Return the set of (pmid, id_1, id_2) keys from a dataset."""
#     return {(row["pmid"], row["id_1"], row["id_2"]) for row in dataset}


# train_keys = _key_set(tokenized_train)
# valid_keys = _key_set(tokenized_valid)
# test_keys = _key_set(tokenized_test)

# train_valid_overlap = train_keys & valid_keys
# train_test_overlap = train_keys & test_keys
# valid_test_overlap = valid_keys & test_keys

# print(f"Train  samples : {len(train_keys)}")
# print(f"Valid  samples : {len(valid_keys)}")
# print(f"Test   samples : {len(test_keys)}")
# print()
# print(f"Train ∩ Valid  : {len(train_valid_overlap)} overlapping pairs")
# print(f"Train ∩ Test   : {len(train_test_overlap)} overlapping pairs")
# print(f"Valid ∩ Test   : {len(valid_test_overlap)} overlapping pairs")

# assert len(train_valid_overlap) == 0, f"Train/Valid overlap: {train_valid_overlap}"
# assert len(train_test_overlap) == 0, f"Train/Test overlap: {train_test_overlap}"
# assert len(valid_test_overlap) == 0, f"Valid/Test overlap: {valid_test_overlap}"
# print("\nOK — no overlap between any splits.")

Train  samples : 8340
Valid  samples : 2323
Test   samples : 2326

Train ∩ Valid  : 0 overlapping pairs
Train ∩ Test   : 0 overlapping pairs
Valid ∩ Test   : 0 overlapping pairs

OK — no overlap between any splits.

In [17]:
accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")
precision_metric = evaluate.load("precision")
recall_metric = evaluate.load("recall")


def compute_metrics(eval_pred):
    """Compute accuracy and globally configured F1 for 9-way relation-type classification."""
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {
        **accuracy_metric.compute(predictions=predictions, references=labels),
        **precision_metric.compute(predictions=predictions, references=labels, average="macro", zero_division=0),
        **recall_metric.compute(predictions=predictions, references=labels, average="macro", zero_division=0),

        "f1_micro": f1_metric.compute(predictions=predictions, references=labels, average="micro")["f1"],
        "f1_macro": f1_metric.compute(predictions=predictions, references=labels, average="macro")["f1"],
        "f1_weighted": f1_metric.compute(predictions=predictions, references=labels, average="weighted")["f1"],
    }

In [18]:
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL,
    num_labels=len(RELATION_LABELS),
    id2label=id2label,
    label2id=label2id,
)

Loading weights: 100%|██████████| 135/135 [00:00<00:00, 4105.98it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bioformers/bioformer-8L
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [19]:
if MODE != "cpu":
    model = model.to(MODE)
print(f"Moving model to {MODE}")


# Train on Train.PubTator; validate on Dev.PubTator during training (Test.PubTator is held out).
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_valid,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

Moving model to cuda

In [19]:
# TRAIN

history = trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.36it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.96it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.63it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.50it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.57it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.47it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.38it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.25it/s]

In [20]:
# Dev split: model selection / early stopping during training.
# print("=== Dev (validation) ===")
# eval_results = trainer.evaluate(tokenized_valid)
# print(eval_results)

# predictions = trainer.predict(tokenized_valid)
# pred_labels = np.argmax(predictions.predictions, axis=1)
# true_labels = predictions.label_ids

# print(
#     classification_report(
#         true_labels,
#         pred_labels,
#         labels=list(range(len(RELATION_LABELS))),
#         target_names=RELATION_LABELS,
#         digits=3,
#         zero_division=0,
#     )
# )

# Test split: held-out final evaluation (run once after training).
print("\n=== Test (held-out) ===")
test_eval_results = trainer.evaluate(tokenized_test)
print(test_eval_results)

test_predictions = trainer.predict(tokenized_test)
test_pred_labels = np.argmax(test_predictions.predictions, axis=1)
test_true_labels = test_predictions.label_ids

print(
    classification_report(
        test_true_labels,
        test_pred_labels,
        labels=list(range(len(RELATION_LABELS))),
        target_names=RELATION_LABELS,
        digits=3,
        zero_division=0,
    )
)

=== Test (held-out) ===

{'eval_loss': 1.6013365983963013, 'eval_accuracy': 0.674548581255374, 'eval_precision': 0.3630184040342277, 'eval_recall': 0.34301371545358894, 'eval_f1_micro': 0.674548581255374, 'eval_f1_macro': 0.34557865832880136, 'eval_f1_weighted': 0.6688796467756986}

                      precision    recall  f1-score   support

Positive_Correlation      0.517     0.609     0.559       325
Negative_Correlation      0.503     0.474     0.488       171
         Association      0.596     0.485     0.535       635
          Comparison      0.000     0.000     0.000         6
         Cotreatment      0.533     0.571     0.552        14
    Drug_Interaction      0.000     0.000     0.000         2
                Bind      0.333     0.111     0.167         9
          Conversion      0.000     0.000     0.000         1
          NoRelation      0.785     0.837     0.810      1163

            accuracy                          0.675      2326
           macro avg      0.363     0.343     0.346      2326
        weighted avg      0.669     0.675     0.669      2326

In [20]:
# append the latest evaluation scores to a JSONL registry for later comparison

RESULTS_FILE = Path("results.jsonl")


def save_result(model: str | AutoModelForSequenceClassification, metrics: dict[str, float] | None = None) -> None:
    """Append one evaluation run to ``RESULTS_FILE``, pulling the rest from the global env.

    Args:
        model: Model identifier, or a loaded model whose ``name_or_path`` is used.
        metrics: Metrics dict from ``Trainer.evaluate``; defaults to the global ``eval_results``.
    """
    metrics = eval_results if metrics is None else metrics
    model_name = model if isinstance(model, str) or isinstance(model, Path) else model.name_or_path
    record = {
        "model_name": str(model_name),
        "model": str(model_name),
        "dataset": DATASET_NAME,
        "f1_average": F1_AVERAGE,
        "metrics": {key.removeprefix("eval_"): value for key, value in metrics.items()},
    }
    with RESULTS_FILE.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, indent=4) + "\n")
    print(f"Appended result for {model} to {RESULTS_FILE}")

In [22]:
save_result(OUT_DIR, test_eval_results)
model.save_pretrained(f"{OUT_DIR}_dump")  # TODO

Appended result for relations-bert-bioformers/bioformer-8L_2026-07-01_22-52-43_BioRed_micro to results.jsonl

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.56it/s]

In [ ]:
OUT_DIR

In [21]:
# call evaluate on checkpoint


def evaluate_checkpoint(
    checkpoint_dir: Path | str,
    eval_dataset: Dataset = tokenized_valid,
    split_name: str = "test",
    args: TrainingArguments = training_args,
    mode: str = MODE,
    labels: list[str] = RELATION_LABELS,
) -> dict[str, float]:
    """Load a fine-tuned checkpoint and evaluate it on ``eval_dataset``.

    Loads the model and tokenizer from ``checkpoint_dir``, runs ``Trainer.evaluate``
    for the configured metrics and prints a per-class ``classification_report``.

    Args:
        checkpoint_dir: Path to a 9-class relation-type checkpoint directory.
        eval_dataset: Tokenized dataset to evaluate on (defaults to the dev split).
        split_name: Human-readable split label for printed reports.
        args: Training arguments reused for the evaluation ``Trainer``.
        mode: Device to place the model on (``"cpu"``, ``"cuda"`` or ``"mps"``).
        labels: Ordered class names used for the classification report.

    Returns:
        The metrics dictionary returned by ``Trainer.evaluate``.
    """
    checkpoint_dir = Path(checkpoint_dir)

    checkpoint_model = AutoModelForSequenceClassification.from_pretrained(checkpoint_dir)
    checkpoint_tokenizer = AutoTokenizer.from_pretrained(checkpoint_dir)
    checkpoint_collator = DataCollatorWithPadding(tokenizer=checkpoint_tokenizer)

    if mode != "cpu":
        checkpoint_model = checkpoint_model.to(mode)

    checkpoint_trainer = Trainer(
        model=checkpoint_model,
        args=args,
        eval_dataset=eval_dataset,
        data_collator=checkpoint_collator,
        compute_metrics=compute_metrics,
    )

    print(f"=== {split_name} ===")
    eval_results = checkpoint_trainer.evaluate(eval_dataset)
    print(eval_results)

    predictions = checkpoint_trainer.predict(eval_dataset)
    pred_labels = np.argmax(predictions.predictions, axis=1)
    true_labels = predictions.label_ids

    print(
        classification_report(
            true_labels,
            pred_labels,
            labels=list(range(len(labels))),
            target_names=labels,
            digits=3,
            zero_division=0,
        )
    )

    return eval_results


#checkpoint_dir = Path("relations-bert-2026-06-11-14-35-34_BioRed_micro") / "checkpoint-5220"
#results = evaluate_checkpoint(checkpoint_dir)

In [ ]:
# iterate over all checkpoints, find the best one based on f1_micro on test


def find_checkpoints(run_dir: Path | str) -> list[Path]:
    """Return all ``checkpoint-*`` directories in ``run_dir`` sorted by global step."""
    run_dir = Path(run_dir)
    return sorted(
        (p for p in run_dir.glob("checkpoint-*") if p.is_dir()),
        key=lambda p: int(p.name.split("-")[-1]),
    )


def score_checkpoint(
    checkpoint_dir: Path | str,
    eval_dataset: Dataset = tokenized_test,
    args: TrainingArguments = training_args,
    mode: str = MODE,
) -> dict[str, float]:
    """Evaluate a single checkpoint and return its metrics without printing a report.

    Args:
        checkpoint_dir: Path to a 9-class relation-type checkpoint directory.
        eval_dataset: Tokenized dataset to score on (defaults to the test split).
        args: Training arguments reused for the evaluation ``Trainer``.
        mode: Device to place the model on (``"cpu"``, ``"cuda"`` or ``"mps"``).

    Returns:
        The metrics dictionary returned by ``Trainer.evaluate``.
    """
    checkpoint_dir = Path(checkpoint_dir)

    checkpoint_model = AutoModelForSequenceClassification.from_pretrained(checkpoint_dir)
    checkpoint_tokenizer = AutoTokenizer.from_pretrained(checkpoint_dir)
    checkpoint_collator = DataCollatorWithPadding(tokenizer=checkpoint_tokenizer)

    if mode != "cpu":
        checkpoint_model = checkpoint_model.to(mode)

    checkpoint_trainer = Trainer(
        model=checkpoint_model,
        args=args,
        eval_dataset=eval_dataset,
        data_collator=checkpoint_collator,
        compute_metrics=compute_metrics,
    )

    return checkpoint_trainer.evaluate(eval_dataset)


RUN_DIR = OUT_DIR
RUN_DIR = "relations-bert-2026-07-01_20-51-41_BioRedPerturbated_micro"
SELECTION_METRIC = f"eval_f1_{F1_AVERAGE}"

checkpoints = find_checkpoints(RUN_DIR)
if not checkpoints:
    raise FileNotFoundError(f"No checkpoint-* directories found under {RUN_DIR}")

checkpoint_results: dict[Path, dict[str, float]] = {}
for checkpoint in checkpoints:
    results = score_checkpoint(checkpoint)
    checkpoint_results[checkpoint] = results
    print(
        f"{checkpoint.name}: "
        f"f1_micro={results['eval_f1_micro']:.4f} "
        f"f1_macro={results['eval_f1_macro']:.4f} "
        f"f1_weighted={results['eval_f1_weighted']:.4f}"
    )

best_checkpoint = max(checkpoint_results, key=lambda c: checkpoint_results[c][SELECTION_METRIC])
print()
print()
print()
print(f"\nBest checkpoint: {best_checkpoint.name} ({SELECTION_METRIC}={checkpoint_results[best_checkpoint][SELECTION_METRIC]:.4f})\n")

test_results = evaluate_checkpoint(best_checkpoint, eval_dataset=tokenized_test, split_name="test")

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 9361.07it/s]

checkpoint-522: f1_micro=0.6397 f1_macro=0.2517 f1_weighted=0.6278

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 9021.71it/s]

checkpoint-1044: f1_micro=0.6574 f1_macro=0.2557 f1_weighted=0.6556

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 9301.36it/s]

checkpoint-1566: f1_micro=0.6702 f1_macro=0.3206 f1_weighted=0.6631

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 8261.01it/s]

checkpoint-2088: f1_micro=0.6776 f1_macro=0.3676 f1_weighted=0.6754

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 9161.23it/s]

checkpoint-2610: f1_micro=0.6629 f1_macro=0.3474 f1_weighted=0.6596

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 7979.39it/s]

checkpoint-3132: f1_micro=0.6569 f1_macro=0.3318 f1_weighted=0.6486

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 8441.35it/s]

checkpoint-3654: f1_micro=0.6621 f1_macro=0.3743 f1_weighted=0.6603

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 8053.31it/s]

checkpoint-4176: f1_micro=0.6642 f1_macro=0.3288 f1_weighted=0.6551

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 9261.04it/s]

checkpoint-4698: f1_micro=0.6745 f1_macro=0.3456 f1_weighted=0.6689

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 7164.74it/s]

checkpoint-5220: f1_micro=0.6672 f1_macro=0.3412 f1_weighted=0.6630




Best checkpoint: checkpoint-2088 (eval_f1_micro=0.6776)

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 9578.75it/s]

=== test ===

{'eval_loss': 0.9777770042419434, 'eval_accuracy': 0.6775580395528805, 'eval_precision': 0.372979670504596, 'eval_recall': 0.3668472367010915, 'eval_f1_micro': 0.6775580395528805, 'eval_f1_macro': 0.36763030325166146, 'eval_f1_weighted': 0.6754129749805942}

                      precision    recall  f1-score   support

Positive_Correlation      0.494     0.631     0.554       325
Negative_Correlation      0.507     0.404     0.450       171
         Association      0.598     0.554     0.575       635
          Comparison      0.286     0.333     0.308         6
         Cotreatment      0.667     0.571     0.615        14
    Drug_Interaction      0.000     0.000     0.000         2
                Bind      0.000     0.000     0.000         9
          Conversion      0.000     0.000     0.000         1
          NoRelation      0.805     0.808     0.807      1163

            accuracy                          0.678      2326
           macro avg      0.373     0.367     0.368      2326
        weighted avg      0.677     0.678     0.675      2326

In [26]:
test_results = evaluate_checkpoint(best_checkpoint, eval_dataset=tokenized_test, split_name="test")

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 9913.22it/s]

=== test ===

{'eval_loss': 0.9777770042419434, 'eval_accuracy': 0.6775580395528805, 'eval_precision': 0.372979670504596, 'eval_recall': 0.3668472367010915, 'eval_f1_micro': 0.6775580395528805, 'eval_f1_macro': 0.36763030325166146, 'eval_f1_weighted': 0.6754129749805942}

                      precision    recall  f1-score   support

Positive_Correlation      0.494     0.631     0.554       325
Negative_Correlation      0.507     0.404     0.450       171
         Association      0.598     0.554     0.575       635
          Comparison      0.286     0.333     0.308         6
         Cotreatment      0.667     0.571     0.615        14
    Drug_Interaction      0.000     0.000     0.000         2
                Bind      0.000     0.000     0.000         9
          Conversion      0.000     0.000     0.000         1
          NoRelation      0.805     0.808     0.807      1163

            accuracy                          0.678      2326
           macro avg      0.373     0.367     0.368      2326
        weighted avg      0.677     0.678     0.675      2326

In [ ]:
save_result(best_checkpoint, test_results)

Appended result for relations-bert-bioformers/bioformer-8L_2026-07-01_22-52-43_BioRed_micro/checkpoint-2088 to results.jsonl

In [22]:
# Load a trained checkpoint (must be 9-class relation-type model, not the old binary one).
CHECKPOINT_DIR = Path(OUT_DIR) / "checkpoint-1260"

model = AutoModelForSequenceClassification.from_pretrained(CHECKPOINT_DIR)
tokenizer = AutoTokenizer.from_pretrained(CHECKPOINT_DIR)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

if MODE != "cpu":
    model = model.to(MODE)

trainer = Trainer(
    model=model,
    args=training_args,
    eval_dataset=tokenized_valid,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)


print("\n=== Test (held-out) ===")
test_eval_results = trainer.evaluate(tokenized_test)
print(test_eval_results)

test_predictions = trainer.predict(tokenized_test)
test_pred_labels = np.argmax(test_predictions.predictions, axis=1)
test_true_labels = test_predictions.label_ids

print(
    classification_report(
        test_true_labels,
        test_pred_labels,
        labels=list(range(len(RELATION_LABELS))),
        target_names=RELATION_LABELS,
        digits=3,
        zero_division=0,
    )
)

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 3864.13it/s]

=== Test (held-out) ===

{'eval_loss': 0.9777770042419434, 'eval_accuracy': 0.6775580395528805, 'eval_precision': 0.372979670504596, 'eval_recall': 0.3668472367010915, 'eval_f1_micro': 0.6775580395528805, 'eval_f1_macro': 0.36763030325166146, 'eval_f1_weighted': 0.6754129749805942}

                      precision    recall  f1-score   support

Positive_Correlation      0.494     0.631     0.554       325
Negative_Correlation      0.507     0.404     0.450       171
         Association      0.598     0.554     0.575       635
          Comparison      0.286     0.333     0.308         6
         Cotreatment      0.667     0.571     0.615        14
    Drug_Interaction      0.000     0.000     0.000         2
                Bind      0.000     0.000     0.000         9
          Conversion      0.000     0.000     0.000         1
          NoRelation      0.805     0.808     0.807      1163

            accuracy                          0.678      2326
           macro avg      0.373     0.367     0.368      2326
        weighted avg      0.677     0.678     0.675      2326

In [31]:
# Manual test with one sample: load a fine-tuned checkpoint from disk and verify formats.
MANUAL_TEST_CHECKPOINT = Path("relations-bert_bioformers-bioformer-8L_2026-07-01_22-52-43_BioRed_micro/checkpoint-2088")

manual_test_model = AutoModelForSequenceClassification.from_pretrained(MANUAL_TEST_CHECKPOINT)
manual_test_tokenizer = AutoTokenizer.from_pretrained(MANUAL_TEST_CHECKPOINT)
manual_test_collator = DataCollatorWithPadding(tokenizer=manual_test_tokenizer)

if MODE != "cpu":
    manual_test_model = manual_test_model.to(MODE)

manual_test_trainer = Trainer(
    model=manual_test_model,
    args=TrainingArguments(output_dir="/tmp/manual-test", eval_strategy="no", report_to="none"),
    data_collator=manual_test_collator,
)

sample_idx = 0
raw_sample = train_dataset[sample_idx]

print("\n=== Raw sample ===")
print("prompt (first 400 chars):")
print(raw_sample["prompt"])

print(f"target_relation: {raw_sample['target_relation']!r}")
print(f"label: {raw_sample['label']} -> {id2label[raw_sample['label']]!r}")

single_ds = tokenized_train.select([sample_idx])
pred_output = manual_test_trainer.predict(single_ds)
pred_label_id = int(np.argmax(pred_output.predictions, axis=1)[0])
true_label_id = int(pred_output.label_ids[0])

print("\n=== Predict (trainer.predict, n=1) ===")
print(f"true: {true_label_id} ({id2label[true_label_id]!r})")
print(f"pred: {pred_label_id} ({id2label[pred_label_id]!r})")
print(f"logits shape: {pred_output.predictions.shape}")
print(pred_output)

Loading weights: 100%|██████████| 137/137 [00:00<00:00, 9156.99it/s]

=== Raw sample ===
prompt (first 400 chars):
Relation: hepatocyte nuclear factor (HNF)-6 -> [MASK] -> Type II (non-insulin-dependent) diabetes mellitus
Context: The transcription factor hepatocyte nuclear factor (HNF)-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in the HNF-6 gene is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of the HNF-6 gene. We then examined them on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of the Pro75Ala polymorphism was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of the polymorphism did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of the HNF-6 gene are not associated with Type II diabetes or with changes in insulin responses to glucose among the Caucasians examined.
target_relation: 'Association'
label: 2 -> 'Association'

=== Predict (trainer.predict, n=1) ===
true: 2 ('Association')
pred: 2 ('Association')
logits shape: (1, 9)
PredictionOutput(predictions=array([[-0.47374496,  0.27556378,  4.6281977 , -2.6418178 , -2.6496956 ,
        -2.4033413 , -0.9345982 , -2.06993   ,  1.3126982 ]],
      dtype=float32), label_ids=array([2]), metrics={'test_loss': 0.06073310971260071, 'test_model_preparation_time': 0.0028, 'test_runtime': 0.0134, 'test_samples_per_second': 74.705, 'test_steps_per_second': 74.705})